# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_enterpise_senior_youth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterpise',
            name='established',
        ),
        migrations.RemoveField(
            model_name='senior',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='youth',
            name='birth',
        ),
    ]
