# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160114_0731'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enterpise',
            new_name='Enterprise',
        ),
    ]
