# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 06:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20160121_1113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='AComment',
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='established',
            field=models.DateField(default=datetime.datetime(2016, 1, 22, 6, 56, 32, 747259)),
        ),
        migrations.AlterField(
            model_name='senior',
            name='birth',
            field=models.DateField(default=datetime.datetime(2016, 1, 22, 6, 56, 32, 746549)),
        ),
        migrations.AlterField(
            model_name='youth',
            name='birth',
            field=models.DateField(default=datetime.datetime(2016, 1, 22, 6, 56, 32, 747852)),
        ),
    ]
