# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 08:58
from __future__ import unicode_literals

import blog.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20160127_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='phone',
            field=blog.models.PhoneField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='established',
            field=models.DateField(default=datetime.datetime(2016, 1, 27, 8, 58, 45, 204150)),
        ),
        migrations.AlterField(
            model_name='senior',
            name='birth',
            field=models.DateField(default=datetime.datetime(2016, 1, 27, 8, 58, 45, 203308)),
        ),
        migrations.AlterField(
            model_name='youth',
            name='birth',
            field=models.DateField(default=datetime.datetime(2016, 1, 27, 8, 58, 45, 204808)),
        ),
    ]
