# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 01:21
from __future__ import unicode_literals

import blog.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20160127_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='established',
            field=models.DateField(default=datetime.datetime(2016, 1, 29, 1, 21, 31, 800612)),
        ),
        migrations.AlterField(
            model_name='post',
            name='phone',
            field=blog.models.PhoneField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='senior',
            name='birth',
            field=models.DateField(default=datetime.datetime(2016, 1, 29, 1, 21, 31, 800009)),
        ),
        migrations.AlterField(
            model_name='youth',
            name='birth',
            field=models.DateField(default=datetime.datetime(2016, 1, 29, 1, 21, 31, 801210)),
        ),
    ]
