# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 03:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import programming.utils


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20160129_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='established',
            field=models.DateField(default=datetime.datetime(2016, 1, 29, 3, 3, 57, 298034)),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to=programming.utils.random_name_upload_to),
        ),
        migrations.AlterField(
            model_name='senior',
            name='birth',
            field=models.DateField(default=datetime.datetime(2016, 1, 29, 3, 3, 57, 297319)),
        ),
        migrations.AlterField(
            model_name='youth',
            name='birth',
            field=models.DateField(default=datetime.datetime(2016, 1, 29, 3, 3, 57, 298622)),
        ),
    ]
