# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 02:20
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0030_auto_20160129_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='established',
        ),
        migrations.RemoveField(
            model_name='senior',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='youth',
            name='birth',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=datetime.datetime(2016, 2, 3, 2, 19, 49, 244130, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=datetime.datetime(2016, 2, 3, 2, 20, 29, 26702, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
